version: '3.2'

services:
  mytest:
    image: avalonlab/maven-openjdk14
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    container_name: mytest
    depends_on:
      - selenoid
      - selenoid-ui
    working_dir: /app
    links:
      - selenoid
    networks:
      - mynet
    command: mvn clean test


  selenoid:
    image: "aerokube/selenoid"
    networks:
      - mynet
    volumes:
      - ".:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "mytestspp_mynet", "-limit", "5", "-retry-count", "2"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - mynet
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  mynet:
    driver:
      bridge

volumes:
  maven-cache:
