version: '3.2'

services:
  mytest:
    image: mytest
    container_name: mytest
    depends_on:
      - selenoid
      - selenoid-ui
    networks:
      - mynet
    build:
      context: .
#    command: mvn clean test
    command: mvn test allure:report
#    environment:
#      - ALLURE_RESULTS_PATH=/app/allure-results
#    ports:
#      - "8081:8081"
    volumes:
      - maven-cache:/root/.m2
#      - allure-results:/app/allure-results
#      - /my_al_rez:/app/allure-results
      - allure-results:/app/target/allure-results

  selenoid:
    image: "aerokube/selenoid"
    networks:
      - mynet
    volumes:
      - ".:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "mytestspp_mynet", "-limit", "5", "-retry-count", "2"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      - mynet
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  mynet:

volumes:
  maven-cache:
  allure-results:
